name: Basic Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '5.*'
env:
  DB_USER: shopware
  DB_PASSWORD: shopware
  DB_HOST: 127.0.0.1
  DB_PORT: 3306
  DB_NAME: shopware
  SW_HOST: localhost
  SW_BASE_PATH: ''
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]
    services:
      mysql:
        image: mariadb:10.6
        env:
          MYSQL_USER: '${{ env.DB_USER }}'
          MYSQL_PASSWORD: '${{ env.DB_PASSWORD }}'
          MYSQL_DATABASE: '${{ env.DB_NAME }}'
          MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        options: '--mount="type=tmpfs,destination=/var/lib/mysql" --health-cmd="mysqladmin ping -h 127.0.0.1" --health-interval=5s --health-timeout=2s --health-retries=3'
        ports:
          - "3306:3306"
    steps:
      - uses: actions/cache@v3
        with:
          path: '/root/.composer/cache/files'
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Composer install
        run: composer --no-interaction install

      - name: Generate .env
        run: |
          cat <<EOF > .env
          DATABASE_URL="mysql://${{ env.DB_USER }}:${{ env.DB_PASSWORD }}@${{ env.DB_HOST }}:${{ env.DB_PORT }}/${{ env.DB_NAME }}"
          ADMIN_EMAIL="admin@example.com"
          ADMIN_NAME="Demo Admin"
          ADMIN_USERNAME="demo"
          ADMIN_PASSWORD="demo"
          SHOP_URL="http://${{ env.SW_HOST }}${{ env.SW_BASE_PATH }}"
          IMPORT_DEMODATA=n
          INSTALL_IMAGES=n
          EOF

      - name: Install
        run: echo 'y' | ./app/bin/install.sh

      - name: Test listing plugins
        run: php bin/console sw:plugin:list

      - name: Test dump theme config
        run: php bin/console sw:theme:dump:configuration

      - name: Test theme compile
        run: php bin/console sw:theme:cache:generate
